# Generated by Django 4.1.7 on 2023-04-06 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('instructores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'competencia',
                'verbose_name_plural': 'competencias',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'programa',
                'verbose_name_plural': 'programas',
            },
        ),
        migrations.CreateModel(
            name='Rap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelosBase.competencia')),
            ],
            options={
                'verbose_name': 'rap',
                'verbose_name_plural': 'raps',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelosBase.programa')),
            ],
            options={
                'verbose_name': 'ficha',
                'verbose_name_plural': 'fichas',
            },
        ),
        migrations.AddField(
            model_name='competencia',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelosBase.programa'),
        ),
    ]
