# Generated by Django 4.1.7 on 2023-03-11 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelosBase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='instructor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencia',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelosBase.programa'),
        ),
    ]
