# Generated by Django 4.1.7 on 2023-04-06 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelosBase', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionesRap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelosBase.ficha')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelosBase.rap')),
            ],
            options={
                'verbose_name': 'asignacion',
                'verbose_name_plural': 'asignaciones',
            },
        ),
    ]
